const shoes = [
    {
        id: 1,
        title: "Dunk Low Goldenrod",
        url: "./assets/shoe 1.png",
        originalPrice: 250,
        salePrice: null,
        rating: 5,
      },
      {
        id: 2,
        title: "Blazer Mid '77 Vintage White",
        url: "./assets/shoe 2.png",
        originalPrice: 150,
        salePrice: null,
        rating: 4.5,
      },
      {
        id: 3,
        title: "Yeezy Boost 350 V2 Zebra",
        url: "./assets/shoe 3.png",
        originalPrice: 399,
        salePrice: null,
        rating: 4.5,
      },
      {
        id: 4,
        title: "NMD Pharrell Human Race Triple Black",
        url: "./assets/shoe 4.png",
        originalPrice: 250,
        salePrice: null,
        rating: 4.5,
      },
      {
        id: 5,
        title: "Air Force 1 White/Black",
        url: "./assets/shoe 5.png",
        originalPrice: 150,
        salePrice: null,
        rating: 4.5,
      },
      {
        id: 6,
        title: "Jordan 1 Retro High OG Court Purple",
        url: "./assets/shoe 6.png",
        originalPrice: 350,
        salePrice: null,
        rating: 4.5,
      },
      {
        id: 7,
        title: "Ultraboost 4.0 DNA White",
        url: "./assets/shoe 7.png",
        originalPrice: 250,
        salePrice: null,
        rating: 4.5,
      },
      {
        id: 8,
        title: "Jordan 4 Retro Black Cat",
        url: "./assets/shoe 8.png",
        originalPrice: 750,
        salePrice: null,
        rating: 5,
      },
      {
        id: 9,
        title: "Jordan 1 Retro High Dior",
        url: "./assets/shoe 9.png",
        originalPrice: 15000,
        salePrice: 12000,
        rating: 4.5,
      },
      {
        id: 10,
        title: "Jordan 3 Retro Cardinal Red",
        url: "./assets/shoe 10.png",
        originalPrice: 399,
        salePrice: 299,
        rating: 4.5,
      },
      {
        id: 11,
        title: "Yeezy Boost 350 V2 Dazzling Blue",
        url: "./assets/shoe 11.png",
        originalPrice: 499,
        salePrice: null,
        rating: 4,
      },
      {
        id: 12,
        title: "Jordan 1 Retro High OG University Blue",
        url: "./assets/shoe 12.png",
        originalPrice: 599,
        salePrice: 499,
        rating: 4,
      },
      {
        id: 13,
        title: "Jordan 1 Retro High OG University Blue",
        url: "./assets/shoe 13.png",
        originalPrice: 599,
        salePrice: 499,
        rating: 4,
      },
      {
        id: 14,
        title: "Jordan 1 Retro High OG University Blue",
        url: "./assets/shoe 14.png",
        originalPrice: 599,
        salePrice: 499,
        rating: 4,
      },
      {
        id: 15,
        title: "Jordan 1 Retro High OG University Blue",
        url: "./assets/shoe 15.png",
        originalPrice: 599,
        salePrice: 499,
        rating: 4,
      },
    ]
    export default shoes